### ISSUE TITLE
Repasar los parámetros de /propsals

### ISSUE THREAD

**Issue by pr3ssh** [open-manifesto-project/open-manifesto-api#4]
* Error en la descripción del parámetro geographical_area

**Comment by Virako** [comment]
¿Los campos budget y non_negotiable que son entonces? O no he entendido bien a lo que te refieres: https://github.com/open-manifesto-project/Open-Manifesto/blob/master/Standard/OpenManifestoV1.1.schema.json#L106

Sobre el parámetro tags y el mecanismo que comentamos en un principio, lo hablamos y tardaba mucho más por que no se hace la búsqueda en DB, habría que traerse todos los datos y tratarlos a parte. Lo hablamos pero si quieres lo cambiamos.
